services:
    db:
        container_name: ${POSTGRES_CONTAINER}
        build:
            context: ../db
            dockerfile: ../docker/db.dockerfile
            args:
                POSTGRES_USER: ${POSTGRES_USER}
                POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
                POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        networks:
            - rede_back
        volumes:
            - db_data:/var/lib/postgresql
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped

    dns:
        container_name: dns
        build:
            context: ../bind
            dockerfile: ../docker/dns.dockerfile
        networks:
            - rede_back
            - rede_front
        expose:
            - "53/udp"
            - "53/tcp"
        volumes:
            - ../bind/named.conf:/etc/bind/named.conf:ro
            - ../bind/zones:/etc/bind/zones:ro
        restart: unless-stopped

    back:
        container_name: backend
        build:
            context: ../back
            dockerfile: ../docker/back.dockerfile
        depends_on:
            db:
                condition: service_healthy
            dns:
                condition: service_started
        environment:
            DB_URL: ${DB_URL}
            BACKEND_KEY: ${BACKEND_KEY}
            ADMIN_USER: ${ADMIN_USER}
            ADMIN_PW: ${ADMIN_PW}
        networks:
            - rede_back
        restart: unless-stopped

    frontend1:
        container_name: frontend1
        build:
            context: ../front
            dockerfile: ../docker/http.dockerfile
        networks:
            - rede_front
        restart: unless-stopped

    frontend2:
        container_name: frontend2
        build:
            context: ../front
            dockerfile: ../docker/http.dockerfile
        networks:
            - rede_front
        restart: unless-stopped

    frontend3:
        container_name: frontend3
        build:
            context: ../front
            dockerfile: ../docker/http.dockerfile
        networks:
            - rede_front
        restart: unless-stopped

    proxy:
        container_name: proxy
        image: nginx:alpine
        depends_on:
            - frontend1
            - frontend2
            - frontend3
            - back
        ports:
            - "80:80"
        volumes:
            - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - rede_front
            - rede_back
        restart: unless-stopped

networks:
    rede_front:
        driver: bridge
    rede_back:
        driver: bridge

volumes:
    db_data:
