version: '3.9'

services:
    db:
        container_name: ${POSTGRES_CONTAINER}
        build:
            context: ../db
            dockerfile: ../docker/db.dockerfile
            args:
                POSTGRES_USER: ${POSTGRES_USER}
                POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
                POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        networks:
            - rede_back
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}

    dns:
        container_name: dns
        build:
            context: ../bind
            dockerfile: ./docker/dns.dockerfile
        networks:
            rede_back:
                ipv4_address: 172.28.0.1
            rede_front:
                ipv4_address: 172.29.0.1
        ports:
            - "53:53/udp"
            - "53:53/tcp"
        volumes:
            - .:/etc/bind

    back:
        container_name: backend
        build:
            context: ../back
            dockerfile: ../docker/back.dockerfile
        depends_on:
            - db
        environment:
            DB_URL: postgresql+psycopg://redes_admin:S3rV3r!n0s@db:5432/app_db

networks:
    rede_front:
        ipam:
            config:
                - subnet: 172.28.0.0/24
    rede_back:
        ipam:
            config:
                - subnet: 172.29.0.0/24
