version: '3.9'

services:
    db:
        container_name: ${POSTGRES_CONTAINER}
        build:
            context: ../db
            dockerfile: ../docker/db.dockerfile
            args:
                POSTGRES_USER: ${POSTGRES_USER}
                POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
                POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        networks:
            rede_back:
                ipv4_address: 172.28.0.2
        volumes:
            - db_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}

    dns:
        container_name: dns
        build:
            context: ../bind
            dockerfile: ../docker/dns.dockerfile
        networks:
            rede_back:
                ipv4_address: 172.28.0.1
            rede_front:
                ipv4_address: 172.29.0.1
        ports:
            - "53:53/udp"
            - "53:53/tcp"
        volumes:
            - ../bind:/etc/bind:ro

    back:
        container_name: backend
        build:
            context: ../back
            dockerfile: ../docker/back.dockerfile
        depends_on:
            - db
        environment:
            DB_URL: ${DB_URL}
            BACKEND_KEY: ${BACKEND_KEY}
            ADMIN_USER: ${ADMIN_USER}
            ADMIN_PW: ${ADMIN_PW}
        networks:
            rede_back:
                ipv4_address: 172.28.0.3
        restart: unless-stopped

    front1:
        container_name: frontend1
        build:
            context: ../front
            dockerfile: ../docker/front.dockerfile
        ports:
            - "80:80"
        networks:
            rede_front:
                ipv4_address: 172.29.0.4
        restart: unless-stopped

    front2:
        container_name: frontend2
        build:
            context: ../front
            dockerfile: ../docker/front.dockerfile
        ports:
            - "80:80"
        networks:
            rede_front:
                ipv4_address: 172.29.0.5
        restart: unless-stopped

    front3:
        container_name: frontend3
        build:
            context: ../front
            dockerfile: ../docker/front.dockerfile
        ports:
            - "80:80"
        networks:
            rede_front:
                ipv4_address: 172.29.0.6
        restart: unless-stopped

networks:
    rede_front:
        ipam:
            config:
                - subnet: 172.29.0.0/24
    rede_back:
        ipam:
            config:
                - subnet: 172.28.0.0/24
volumes:
    db_data:
