services:
    db:
        container_name: ${POSTGRES_CONTAINER}
        build:
            context: ../db
            dockerfile: ../docker/db.dockerfile
            args:
                POSTGRES_USER: ${POSTGRES_USER}
                POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
                POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        networks:
            rede_back:
                ipv4_address: 10.10.0.2
        dns:
            - 10.10.0.10
        volumes:
            - db_data:/var/lib/postgresql
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped

    dns:
        container_name: dns
        build:
            context: ../bind
            dockerfile: ../docker/dns.dockerfile
        networks:
            rede_back:
                ipv4_address: 10.10.0.10
            rede_front:
                ipv4_address: 10.11.0.10
        ports:
            - "53:53/udp"
            - "53:53/tcp"
        volumes:
            - ../bind/named.conf:/etc/bind/named.conf:ro
            - ../bind/zones:/etc/bind/zones
        restart: unless-stopped

    back:
        container_name: backend
        build:
            context: ../back
            dockerfile: ../docker/back.dockerfile
        depends_on:
            - db
            - dns
        dns:
            - 10.10.0.10
            - 1.1.1.1
        environment:
            DB_URL: ${DB_URL}
            BACKEND_KEY: ${BACKEND_KEY}
            ADMIN_USER: ${ADMIN_USER}
            ADMIN_PW: ${ADMIN_PW}
        networks:
            rede_back:
                ipv4_address: 10.10.0.3
            rede_front:
                ipv4_address: 10.11.0.3
        restart: unless-stopped

    frontend1:
        container_name: frontend1
        build:
            context: ../front
            dockerfile: ../docker/http.dockerfile
            args:
                HOSTNAME: frontend1
        ports:
            - "3000:80"
        dns:
            - 10.11.0.10
        networks:
            rede_front:
                ipv4_address: 10.11.0.4
        restart: unless-stopped

    frontend2:
        container_name: frontend2
        build:
            context: ../front
            dockerfile: ../docker/http.dockerfile
            args:
                HOSTNAME: frontend2
        dns:
            - 10.11.0.10
        networks:
            rede_front:
                ipv4_address: 10.11.0.5
        restart: unless-stopped

    frontend3:
        container_name: frontend3
        build:
            context: ../front
            dockerfile: ../docker/http.dockerfile
            args:
                HOSTNAME: frontend3
        dns:
            - 10.11.0.10
        networks:
            rede_front:
                ipv4_address: 10.11.0.6
        restart: unless-stopped

    proxy:
        container_name: proxy
        image: nginx:alpine
        depends_on:
            - frontend1
            - frontend2
            - frontend3
            - back
        ports:
            - "80:80"
        volumes:
            - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
        dns:
            - 10.11.0.10
        networks:
            rede_front:
                ipv4_address: 10.11.0.7
        restart: unless-stopped

    dns-updater:
        container_name: dns-updater
        build:
            context: ../bind
            dockerfile: ../docker/updater.dockerfile
        depends_on:
            - dns
        networks:
            rede_front:
                ipv4_address: 10.11.0.20
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ../bind/zones:/zones
        environment:
            - ZONE_FILE=/zones/db.aredanvisa.local
            - FRONTENDS=frontend1,frontend2,frontend3
        restart: unless-stopped


volumes:
    db_data:

networks:
    rede_back:
        driver: bridge
        ipam:
            config:
                - subnet: 10.10.0.0/24
    rede_front:
        driver: bridge
        ipam:
            config:
                - subnet: 10.11.0.0/24
